### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by satheeshkola-532** [baichuan-inc/Baichuan-Omni-1.5#3]
Hello @jhxu-org and team, Congratulations on achieving this great work, 
When i run an inference for multiple image + query (medical iu xray test dataset) in a loop , it's throwing the cuda out of memory issue,(I have increased the max token length from 50 to 200 ) Is there any ways to resolve this issue? Thanks in advance.

And one more thing on keeping audiogen_flag = False in  on Baichuan-Omni-1.5/web_demo/vision_s2s_gradio_demo_cosy_multiturn.py, we need to handle the case of empty audio in the parse_assistant_content() method 

This:
 for t, w in result:
        text += t
        wav_pkg = load_audio(w["path"])
        wave.append(wav_pkg[1])
    wave = np.concatenate(wave, axis=0)
   
Replace with:
for t, w in result:
        text += t
        wav_pkg = load_audio(w["path"])
        wave.append(wav_pkg[1])

    # **Fix**: Handle empty `wave` case properly
    if wave:
        wave = np.concatenate(wave, axis=0)
        return text, (wav_pkg[0], wave)
    else:
        return text, None  # Return None if no audio generated

**Comment by satheeshkola-532** [comment]
> Hello [@jhxu-org](https://github.com/jhxu-org) and team, Congratulations on achieving this great work, When i run an inference for multiple image + query (medical iu xray test dataset) in a loop , it's throwing the cuda out of memory issue,(I have increased the max token length from 50 to 200 ) Is there any ways to resolve this issue? Thanks in advance.
> 
> And one more thing on keeping audiogen_flag = False in on Baichuan-Omni-1.5/web_demo/vision_s2s_gradio_demo_cosy_multiturn.py, we need to handle the case of empty audio in the parse_assistant_content() method
> 
> This: for t, w in result: text += t wav_pkg = load_audio(w["path"]) wave.append(wav_pkg[1]) wave = np.concatenate(wave, axis=0)
> 
> Replace with: for t, w in result: text += t wav_pkg = load_audio(w["path"]) wave.append(wav_pkg[1])
> 
> ```
> # **Fix**: Handle empty `wave` case properly
> if wave:
>     wave = np.concatenate(wave, axis=0)
>     return text, (wav_pkg[0], wave)
> else:
>     return text, None  # Return None if no audio generated
> ```

Out of Memory issue resolved on clearing the chat history after each iteration.

**Comment by AdonLee072348** [comment]
Thanks for your attention very much, we have updated the code of web demo. You can clear the chat history when cuda out of memory.
